# Numpy

Numpy is a library which provides support for large, homogeneous, multi-dimensional arrays and matrices

In [2]:
import numpy as np

## Creating a list in Numpy

### Creating an array from a list

In [27]:
list1 = [10, 20, 30]
list1

[10, 20, 30]

In [8]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [6]:
type(arr1)

numpy.ndarray

## Using arrange to create an array

The difference between array and arrange is that array takes in a list and turns it into an array, whereas arrange creates an array from a range of numbers.

In [7]:
arr2 = np.arange(10, 20, 1) # (start, stop, step-size)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Multideminsional arrays

### Combining two list - Two-dimensional arrays

When we combine arrays together, we can add dimensions. Combining two arrays gives us a 2d array!

This creates a matrix for us on which we can perform matrix operations.

In [12]:
# let's create a new list to join onto the first list 
list2 = [40, 50, 60]

# join the lists
list3 = [list1, list2]

# create an array out of the joined lists
arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [14]:
# lets find the shape of that array
# we have a 2d array, with 2 elements in the first instance and 3 in the second

arr3.shape

(2, 3)

### Three-dimensional arrays

In [29]:
arr3dim = np.array([[[1,2,3], [3,4,5]], [[5,6,7],[7,8,9]]])
arr3dim

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [16]:
arr3dim.shape

(2, 2, 3)

## Using Arrays and Scalars

Numpy arrays (or ndarray) allow us to perform matrix operations.

In [30]:
# for example, we can use simple multiplication
arr3dim * 3

array([[[ 3,  6,  9],
        [ 9, 12, 15]],

       [[15, 18, 21],
        [21, 24, 27]]])

In [28]:
# how is this different than trying to do: 
list1 * 3

# lists and arrays are treated differently, see below:

[10, 20, 30, 10, 20, 30, 10, 20, 30]

In [31]:
# we can actually multiply an array with another array

# creat a new array with the same size as arr1
arr11 = np.array(list2)

# multiply arrays
arr1 * arr11

array([ 400, 1000, 1800])

### Can we multiply arrays of different shapes?

In [32]:
arr1 * arr2

ValueError: operands could not be broadcast together with shapes (3,) (10,) 

The answer is NO!

### It is possible to multiply arrays of different dimensions, but they need the same element size!

In [33]:
arr1 * arr3dim

array([[[ 10,  40,  90],
        [ 30,  80, 150]],

       [[ 50, 120, 210],
        [ 70, 160, 270]]])

# Practice

In [40]:
# 1d array
my_list = [1,2,3]
my_arr = np.array(my_list)
my_arr

#2d array
my_2d_arr = np.array([[1,2,3,4],[1,2,5,6],[4,5,6,7]])
my_2d_arr.shape

#3d array
my_3d_arr = np.array([[[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7],[5,6,7,8]],
                      [[2,3,4,5],[5,4,3,2],[6,5,4,3],[7,6,5,4],[8,7,6,5]]])
my_3d_arr.shape

(2, 5, 4)

### Accessing the values inside ndarrays

Let's take arr3 as our examply, this was a 2d array

In [44]:
# how can we access the 60?
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [46]:
# we can use indexing
arr3[1][2]

np.int64(60)

In [47]:
# we can use a comma!
arr3[1,2]

np.int64(60)

In [48]:
# how can I get the bottom 'row' of this ndarray?
arr3[1]

array([40, 50, 60])

In [50]:
# how about if we just want the last COLUMN?
# meaning everything, so see below
arr3[:,2]
# for each array in this 2d array, give me index 2

array([30, 60])

## Statistical functions and arrays

There are a number of built-in statistical functions we can use with numpy

In [52]:
# finding the sum of all values 
arr3.sum()

np.int64(210)

In [54]:
# finding the sum of all columns
arr3.sum(0)

array([50, 70, 90])

In [56]:
# finding the sum of all rows 
arr3.sum(1)

array([ 60, 150])

In [57]:
# finding the mean 
arr3.mean()

np.float64(35.0)

In [59]:
# finding the standard deviation 
arr3.std()

np.float64(17.07825127659933)

In [60]:
# finding the variance 
arr3.var()

np.float64(291.6666666666667)

In [61]:
# finding min value
arr3.min()

np.int64(10)

In [62]:
# finding max value
arr3.max()

np.int64(60)

## Iterating through ndarrays

Simpliest way is to use a simple loop

In [63]:
# for a 1d array 
for x in arr1:
    print(x)

10
20
30


In [64]:
# how about an n-dimensional array? we can use nested loops
for dim in arr3:
    for num in dim:
        print(num)
# arr3 is 2d

10
20
30
40
50
60


In [65]:
# there is another way! we can use nditer
# this can be used in simple scenarios, but also very complex ones
# tends to be much cleaner for nested loops

for x in np.nditer(arr3):
    print(x)

#recommended

10
20
30
40
50
60


### Saving and loading in numpy

In [66]:
# to save an array as a file 
np.save('name_of_file', arr3)

In [67]:
# load the file 
np.load('name_of_file.npy')

array([[10, 20, 30],
       [40, 50, 60]])

In [68]:
# saving as a txt 
np.savetxt('file_name.txt', arr3, delimiter=',')

In [69]:
# loading a txt
np.loadtxt('file_name.txt', delimiter=',')

array([[10., 20., 30.],
       [40., 50., 60.]])